#!/bin/bash - 
#===============================================================================
#
#          FILE: start-container.sh
# 
#         USAGE: ./start-container.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (), 
#  ORGANIZATION: 
#       CREATED: 08/22/2015 18:27
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

TOPDIR="$(dirname "$0")/.."
BASEDIR="${TOPDIR}/base/arch-base"
CONTAINERDIR="$(dirname "$0")"
MNTOPTS="-o lowerdir=${BASEDIR},upperdir=${CONTAINERDIR}/rw,workdir=${CONTAINERDIR}/work"

mount -t overlay ${MNTOPTS} overlay mnt

systemd-nspawn --boot \
	       --machine=nginx \
	       --directory="${CONTAINERDIR}/mnt" \
	       --network-bridge=vboxbridge0

